version: "2"

linters:
  default: standard
  enable:
    - gocritic
    - misspell
    - nolintlint
    - unconvert
    - unparam
    - ginkgolinter
    - zerologlint

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - hugeParam
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unparam

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/noksa/helm-in-pod

run:
  build-tags:
    - e2e
