name: "in-pod"
version: "0.2.0"
usage: "Run any command using privileged pod in a k8s cluster"
command: "$HELM_PLUGIN_DIR/bin/in-pod"
useTunnel: false
ignoreFlags: false
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  upgrade: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"