name: CI

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Install kind
        uses: helm/kind-action@v1
        with:
          install_only: true

      - name: Install kind cluster
        run: make test-e2e-setup

      - name: Run unit tests
        run: |-
          export KUBECONFIG="${GITHUB_WORKSPACE}/e2e/.kubeconfig"
          make test

      - name: Run e2e tests
        run: |-
          export KUBECONFIG="${GITHUB_WORKSPACE}/e2e/.kubeconfig"
          make test-e2e
